var Loc= {"location":[
{"locname" : "Pintu Utama", "info" : "pintu utama gedung Agape", "coorx" : "1.9","coory" : "0.2", "coorz" : "8.8"},
{"locname" : "Humas", "info" : "ruang Humas", "coorx" : "-6","coory" : "0.2", "coorz" : "7"},
{"locname" : "Admisi", "info" : "ruang Admisi", "coorx" : "-2.2","coory" : "0.2", "coorz" : "6.7"},
{"locname" : "BRI", "info" : "bank BRI", "coorx" : "6.3","coory" : "0.2", "coorz" : "7"},
{"locname" : "Kantin", "info" : "kantin UKDW", "coorx" : "6","coory" : "0.2", "coorz" : "-4.5"},
{"locname" : "Toko Buku", "info" : "toko buku UKDW", "coorx" : "-6.3","coory" : "0.2", "coorz" : "1.1"},
{"locname" : "LPPM", "info" : "ruang LPPM", "coorx" : "-6.3","coory" : "0.2", "coorz" : "-5"},
{"locname" : "Design Center", "info" : "ruang design arsitek & despro", "coorx" : "-1","coory" : "0.2", "coorz" : "-5"},
{"locname" : "Magister Managemen", "info" : "ruang Magister Managemen", "coorx" : "-6","coory" : "1.7", "coorz" : "7"},
{"locname" : "Tax Center", "info" : "ruang Tax Center", "coorx" : "-2.2","coory" : "1.7", "coorz" : "6.7"},
{"locname" : "PPLK", "info" : "ruang PPLK", "coorx" : "7","coory" : "1.7", "coorz" : "7.8"},
{"locname" : "Puspindika", "info" : "ruang Puspindika", "coorx" : "7","coory" : "1.7", "coorz" : "4"},
{"locname" : "Lab Komputer", "info" : "lab komputer UKDW", "coorx" : "0","coory" : "1.7", "coorz" : "-5.5"},
{"locname" : "FTI", "info" : "ruang dosen FTI", "coorx" : "-0.5","coory" : "3.2", "coorz" : "6.8"},
{"locname" : "Teologia", "info" : "ruang dosen Fakultas Teologia", "coorx" : "-6","coory" : "3.2", "coorz" : "-5"},
{"locname" : "Inkubasi", "info" : "lab Inkubasi", "coorx" : "6.5","coory" : "3.2", "coorz" : "-3.5"},
{"locname" : "Bioteknologi", "info" : "ruang dosen Fakultas Bioteknologi", "coorx" : "-2","coory" : "4.7", "coorz" : "7"},
{"locname" : "Bisnis", "info" : "ruang dosen Fakultas Bisnis", "coorx" : "1.5","coory" : "4.7", "coorz" : "7"},
{"locname" : "Video Confrence", "info" : "ruang Video Confrence", "coorx" : "6.5","coory" : "4.7", "coorz" : "-2"},
{"locname" : "Lab SI", "info" : "Lab khusus SI", "coorx" : "2.2","coory" : "4.7", "coorz" : "-5"},
{"locname" : "PHKI", "info" : "ruang PHKI", "coorx" : "-2","coory" : "4.7", "coorz" : "-5.5"},
{"locname" : "Pasca Sarjana", "info" : "ruang Pasca Sarjana", "coorx" : "-6","coory" : "4.7", "coorz" : "-2"},
{"locname" : "Arsitektur & Design", "info" : "ruang dosen Arsitektur & Design", "coorx" : "0","coory" : "6.2", "coorz" : "7"},
{"locname" : "Program Magister", "info" : "ruang Program Magister", "coorx" : "6.5","coory" : "6.2", "coorz" : "-4"},
{"locname" : "Humaniora", "info" : "ruang dosen Humaniora", "coorx" : "-1","coory" : "6.2", "coorz" : "-5"},
{"locname" : "Studio A5 1", "info" : "studio Arsitektur & Design A5 no 1", "coorx" : "6.5","coory" : "6.2", "coorz" : "1.5"},
{"locname" : "Studio A5 3", "info" : "studio Arsitektur & Design A5 no 3", "coorx" : "-6","coory" : "6.2", "coorz" : "1"},
{"locname" : "Studio A5 4", "info" : "studio Arsitektur & Design A5 no 4", "coorx" : "-6","coory" : "6.2", "coorz" : "-1.5"},
{"locname" : "Studio A5 5", "info" : "studio Arsitektur & Design A5 no 5", "coorx" : "-6","coory" : "6.2", "coorz" : "-4"},
{"locname" : "Studio A6 1", "info" : "studio Arsitektur & Design A6 no 1", "coorx" : "6","coory" : "7.7", "coorz" : "7"},
{"locname" : "Studio A6 2", "info" : "studio Arsitektur & Design A6 no 2", "coorx" : "6","coory" : "7.7", "coorz" : "0"},
{"locname" : "Studio A6 3", "info" : "studio Arsitektur & Design A6 no 3", "coorx" : "5.5","coory" : "7.7", "coorz" : "-5"},
{"locname" : "Studio A6 4", "info" : "studio Arsitektur & Design A6 no 4", "coorx" : "1.5","coory" : "7.7", "coorz" : "-5"},
]};